name: faker
version: 0.0.1
description: A library for generating fake data
homepage: https://github.com/drager/faker
author: Jesper Håkansson <jesper@jesperh.se>
dev_dependencies:
  guinness: '>=0.1.17 <0.2.0'
  unittest: '>=0.11.0 <0.12.0'
  matcher: any
