name: faker
version: 1.0.0
description: A library for generating fake data
homepage: https://github.com/drager/faker
author: Jesper Håkansson <jesper@jesperh.se>
environment:
  sdk: '>=2.0.0 <3.0.0'
dev_dependencies:
  test: ^1.2.0
